### PR TITLE
add option to use remote config files

### LINKED ISSUE #1: [Q/FR] Sync labels based on a config file within another repository
Greetings there,

I am curious if it where at al passible to allow the configuration of this action to work with both `source-repo` and `config-file` to have one 'configuration repository to rule them all'?
This behaviour is already somewhat possible to realize, however it is limited to only one configuration by having this action run in one repo on a `config-file` to sync its labels and then any 'dependent' repos to clone those via the `source-repo` config.

Theoretically it should be possible to realize since GitHub's API allows for [direct file access](https://docs.github.com/en/rest/reference/repos#get-repository-content) and I am interested in looking into adding this functionality to this Action if it wasn't already planed.

So the question/feature-request boils down to: have you planed/are you planing of adding this functionality, or would you accept a PR adding such?

Thank you for your work so far!

### PR DESCRIPTION
**Pull request by h1dden-da3m0n**
### Description

This PR aims to add the option to load/read a label configuration file from a remote repository.
Thereby the configuration source can be one of the following:
* `localFile` - The config file is contained within the same repo as the workflow
* `remoteFile` - The config file is contained within another repository, but is still a config file like the `localFile`
* `repository` - The labels of a given repository should be cloned to the local one

Note: my TypeScript skills are not the best, so please feel free to give me feedback if I missed some best practise

### Changes

* add logic to read remote config file

### Issue(s)

* closes #1

### CODE REVIEW

**Comment by h1dden-da3m0n** [comment]
:man_facepalming: Just realized I hard coded the 'default' branch for `remoteFile` to `main`.

3 ways to fix it:
1. determine the default branch of the remote repo via a API call
2. add an option to overwrite it
3. a combination of the 2

I will deal with that tomorrow

**Comment by EndBug** [comment]
Thank you so much for the PR! I'm pretty busy these days, but I'll be happy to review it!
Since you still need to change that thing, feel free to request a review when you think the PRs ready ;)
(Remember to test it)

**Comment by h1dden-da3m0n** [comment]
Hi @EndBug,

thank you for your quick response! I feel you on the limited time :sweat_smile:.
Regardless, added the `remoteConfig` default branch discovery logic + an manual overwrite option for the action.
I also tested both:
* manually configured: https://github.com/h1dden-da3m0n/test-repo/runs/2754143533?check_suite_focus=true
* auto discovered default-branch: https://github.com/h1dden-da3m0n/test-repo/runs/2754126347?check_suite_focus=true

I will likely make sure I did not mess up the other options by using an enum now over a simple bool to determine what option to use, but the main task should be done (I think).

(I think this is thereby ready 4 review once you find the time ofc :wink: )

**Comment by h1dden-da3m0n** [comment]
rebased and actually found another oversight on my end :sweat_smile:

**Comment by h1dden-da3m0n** [comment]
hey @EndBug, any chance you could find some time to get this one reviewed? pretty please, I would love to use this with a suit of CI updates I am working on rn.

**Comment by EndBug** [comment]
@h1dden-da3m0n Sure! Now I'm less busy, I'll try to catch up with everything ;)

**Review by EndBug — COMMENTED** [review]
Question: why don't we allow the users to just put a URL as the config file? 
This way they have to provide the link to the JSON file they want to use and they're not limited to using GitHub (they could, for example, use GitLab or Unpkg,com)
This would also allow us not to have to read the repo and the branch: if they're using GitHub they'll just put their ref in the URL.

**Comment by h1dden-da3m0n** [comment]
@EndBug 

Hmmm, yes, I guess that would work too ... personally I think that though to be a bit excessive (thinking that ppl would use this action and host the config somewhere else than GitHub).
I can re-write the logic to work like you that, if you want, or add just an additional configuration that mimics that behaviour.

Personally, I obviously prefer this method, since it 'abstracts' the url. However, I agree that it would be simpler logic if it where just 'provide the url' and done.

**Comment by EndBug** [comment]
@h1dden-da3m0n Again: I'm really sorry this is taking me so long 😅 
I've made a few changes, how does this look to you?

**Comment by h1dden-da3m0n** [comment]
no worries, I never expect things to go :snaps_fingers: and done, we all have private responsibilities and lives to manage :wink: 
I will have a look asap, but from my brief glance looks good :+1: 
Thank you for the collaboration on this, I would have done it myself if your review would have been a 'change requested' but I wasn't sure so I left it by just giving my 2 cents to your question.

**Comment by h1dden-da3m0n** [comment]
Hi @EndBug,

As far as I am able to tell your update to my changes LGTM.
I might still find this approach a bit odd, but I guess that's personal preference and after all it does the same/what I wanted to  accomplish in the first place :smiley: .

Thank you and let me know if I can or should change/do.

**Review by EndBug — APPROVED** [review]
Well, seems ready to merge to me!
@h1dden-da3m0n Can I ask you for one last review before merging and publishing the new version?

**Review by h1dden-da3m0n — COMMENTED** [review]
Hey @EndBug,

your changes LGTM, thank you for chiming in on this!

**Comment by EndBug** [comment]
@all-contributors please add @h1dden-da3m0n for their code

**Pull request merged**
