### PR TITLE
Pretty print the diff

### PR DESCRIPTION
**Pull request by kenodegard**
Provide a cleaner diff output making it easier to inspect the `dry-run` results.

Depends on DefinitelyTyped/DefinitelyTyped#58296

### Added labels

```
type::bug [missing]
☀️ → type::bug
☀️ → #b60205
☀️ → describes erroneous operation
```

### Updated labels

```
type::feature [changed]
feature → type::feature
#888888 → #fff2cc
user requested new functionality → request for a new feature or capability
```
### Deleted labels

```
question [added]
question → ⚰️ 
#d4c5f9 → ⚰️ 
user asked question → ⚰️ 
```

### CODE REVIEW

**Review by EndBug — APPROVED** [review]
LGTM!

I have merged the other PR and now there's a merge conflict with the build file, you should be able to fix it by just re-building.
After that this is ready to be merged 👍🏻

**Comment by kenodegard** [comment]
@EndBug rebased and everything looks good! thanks again for your quick responses!

**Comment by EndBug** [comment]
Thank you for the contributions 😄

**Comment by EndBug** [comment]
@all-contributors please add @kenodegard for their code contributions

**Comment by EndBug** [comment]
Everything has been published in `v2.1.0` (also `v2` and `latest`)
Thanks for the contributions ❤️

**Pull request merged**
